version = 0.1
[default.deploy.parameters]
stack_name = "twitter"
resolve_s3 = true
s3_prefix = "twitter"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
