definitions:
  common.Image:
    properties:
      cloud_name:
        type: string
      extension:
        type: string
      height:
        type: integer
      id:
        type: integer
      url:
        type: string
      width:
        type: integer
    type: object
  common.SimpleUser:
    properties:
      avatar:
        $ref: '#/definitions/common.Image'
      created_at:
        type: string
      first_name:
        type: string
      id:
        $ref: '#/definitions/common.UID'
      last_name:
        type: string
      role:
        type: string
      status:
        type: integer
      updated_at:
        type: string
    type: object
  common.UID:
    type: object
  common.simpleSuccessRes:
    properties:
      data: {}
    type: object
  common.successRes:
    properties:
      data: {}
      filter: {}
      paging: {}
    type: object
  tokenprovider.Token:
    properties:
      created_at:
        type: string
      expiry:
        type: integer
      token:
        type: string
    type: object
  tweetmodel.Tweet:
    properties:
      created_at:
        type: string
      id:
        $ref: '#/definitions/common.UID'
      image:
        items:
          $ref: '#/definitions/common.Image'
        type: array
      status:
        type: integer
      text_content:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/common.SimpleUser'
    type: object
  tweetmodel.TweetCreate:
    properties:
      imageIDs:
        items:
          type: string
        type: array
      text_content:
        type: string
    type: object
  usermodel.User:
    properties:
      avatar:
        $ref: '#/definitions/common.Image'
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        $ref: '#/definitions/common.UID'
      last_name:
        type: string
      phone:
        type: string
      role:
        type: string
      status:
        type: integer
      updated_at:
        type: string
    type: object
  usermodel.UserCreate:
    properties:
      avatar:
        $ref: '#/definitions/common.Image'
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    type: object
  usermodel.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login
      operationId: login
      parameters:
      - description: User
        in: body
        name: cinema
        required: true
        schema:
          $ref: '#/definitions/usermodel.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.simpleSuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/tokenprovider.Token'
              type: object
      summary: Login
      tags:
      - users
  /profile:
    get:
      consumes:
      - application/json
      description: Get profile
      operationId: get-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.simpleSuccessRes'
            - properties:
                data:
                  $ref: '#/definitions/usermodel.User'
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get profile
      tags:
      - users
  /register:
    post:
      consumes:
      - application/json
      description: Register
      operationId: register
      parameters:
      - description: User
        in: body
        name: cinema
        required: true
        schema:
          $ref: '#/definitions/usermodel.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.simpleSuccessRes'
            - properties:
                data:
                  type: string
              type: object
      summary: Register
      tags:
      - users
  /tweets:
    get:
      consumes:
      - application/json
      description: List tweet
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: User ID
        in: query
        name: user_id
        type: string
      - description: Search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.successRes'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/tweetmodel.Tweet'
                  type: array
              type: object
      summary: List tweet
      tags:
      - tweets
    post:
      consumes:
      - application/json
      description: Create tweet
      parameters:
      - description: Tweet
        in: body
        name: tweet
        required: true
        schema:
          $ref: '#/definitions/tweetmodel.TweetCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.simpleSuccessRes'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create tweet
      tags:
      - tweets
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.simpleSuccessRes'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Upload file
      tags:
      - uploads
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
